//
// Generated file, do not edit! Created by nedtool 5.6 from node/communication/routing/cluster/gambac/GAMBACPacket.msg.
//

#ifndef __GAMBACPACKET_M_H
#define __GAMBACPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "node/communication/routing/RoutingPacket_m.h"
#include "helpStructures/GeoMathHelper.h"
typedef std::vector<int> IntVector;
// }}

/**
 * Enum generated from <tt>node/communication/routing/cluster/gambac/GAMBACPacket.msg:30</tt> by nedtool.
 * <pre>
 * enum GAMBACPacket_Type
 * {
 *     GAMBAC_ROUTING_CONTROL_PACKET = 1;
 *     GAMBAC_ROUTING_DATA_PACKET = 2;
 *     GAMBAC_ROUTING_JOIN_PACKET = 3;
 *     GAMBAC_ROUTING_ADV_PACKET = 4;
 *     DATA_PACKET_FROM_MAC = 5;
 * }
 * </pre>
 */
enum GAMBACPacket_Type {
    GAMBAC_ROUTING_CONTROL_PACKET = 1,
    GAMBAC_ROUTING_DATA_PACKET = 2,
    GAMBAC_ROUTING_JOIN_PACKET = 3,
    GAMBAC_ROUTING_ADV_PACKET = 4,
    DATA_PACKET_FROM_MAC = 5
};

/**
 * Class generated from <tt>node/communication/routing/cluster/gambac/GAMBACPacket.msg:39</tt> by nedtool.
 * <pre>
 * packet GAMBACPacket extends RoutingPacket
 * {
 *     int GAMBACPacketKind \@enum(GAMBACPacket_Type);
 *     int sourceCH;
 *     int schedule[];
 *     double remainingEnergy;
 *     IntVector isCH;
 *     IntVector nextCH;
 *     IntVector trace;
 * }
 * </pre>
 */
class GAMBACPacket : public ::RoutingPacket
{
  protected:
    int GAMBACPacketKind;
    int sourceCH;
    int *schedule; // array ptr
    unsigned int schedule_arraysize;
    double remainingEnergy;
    IntVector isCH;
    IntVector nextCH;
    IntVector trace;

  private:
    void copy(const GAMBACPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GAMBACPacket&);

  public:
    GAMBACPacket(const char *name=nullptr, short kind=0);
    GAMBACPacket(const GAMBACPacket& other);
    virtual ~GAMBACPacket();
    GAMBACPacket& operator=(const GAMBACPacket& other);
    virtual GAMBACPacket *dup() const override {return new GAMBACPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getGAMBACPacketKind() const;
    virtual void setGAMBACPacketKind(int GAMBACPacketKind);
    virtual int getSourceCH() const;
    virtual void setSourceCH(int sourceCH);
    virtual void setScheduleArraySize(unsigned int size);
    virtual unsigned int getScheduleArraySize() const;
    virtual int getSchedule(unsigned int k) const;
    virtual void setSchedule(unsigned int k, int schedule);
    virtual double getRemainingEnergy() const;
    virtual void setRemainingEnergy(double remainingEnergy);
    virtual IntVector& getIsCH();
    virtual const IntVector& getIsCH() const {return const_cast<GAMBACPacket*>(this)->getIsCH();}
    virtual void setIsCH(const IntVector& isCH);
    virtual IntVector& getNextCH();
    virtual const IntVector& getNextCH() const {return const_cast<GAMBACPacket*>(this)->getNextCH();}
    virtual void setNextCH(const IntVector& nextCH);
    virtual IntVector& getTrace();
    virtual const IntVector& getTrace() const {return const_cast<GAMBACPacket*>(this)->getTrace();}
    virtual void setTrace(const IntVector& trace);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GAMBACPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GAMBACPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __GAMBACPACKET_M_H

